# Generated by cucumber-sinatra. (2013-04-03 15:30:31 -0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara-webkit'
require 'rspec'

Capybara.javascript_driver = :webkit
Capybara.app = Base::App

class BaseWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers

	def app
		run Base::App
	end
end

World do
  BaseWorld.new
end
